Mungge/Fleecy-Cloud

backend/Dockerfile
docker-compose.yml
frontend/Dockerfile
frontend/next.config.ts

For the docker environment It starts with production mode.

♻️ Update the files for the dockerlization.

---

frontend/src/middleware.ts

- Protect all routes with token validation
- Auto-redirect unauthenticated users to login
- Auto-redirect authenticated users to dashboard

♻️ Refactor global authentication middleware.

---

backend/handlers/federated_learning_handler.go
backend/utils/terraform.go

1. Remove a not used import statement
2. Add a CloudConnectionID in CreateFederatedLearningRequest struct.

🐛 Fix an Error on Backend.

---

backend/models/cloud_price.go

✨ Add cloud_price model

---

frontend/src/components/dashboard/federated-learning/federated-learning-content.tsx

- Remove ESLint disable comment for react-hooks/exhaustive-deps
- Add useRef-based initialization guard to prevent multiple API calls
- Maintain single execution on mount while following React hooks rules

⚰️ Resolve useEffect dependency warnings without infinite renders

---

backend/handlers/participant_handler.go
backend/models/participant.go
frontend/package-lock.json
frontend/src/components/dashboard/participants/participants-content.tsx
frontend/src/types/participant.ts

Add a Region attribute to Particpants.

---

frontend/src/components/dashboard/aggregator/aggregator-create-content.tsx
frontend/src/components/dashboard/aggregator/aggregator.types.ts
frontend/src/components/dashboard/aggregator/components/AggregatorSelectionModal.tsx
frontend/src/components/dashboard/aggregator/components/AggregatorSettings.tsx
frontend/src/components/dashboard/aggregator/components/CreationStatus.tsx
frontend/src/components/dashboard/aggregator/components/FederatedLearningInfo.tsx
frontend/src/components/dashboard/aggregator/components/ProgressSteps.tsx
frontend/src/components/dashboard/aggregator/hooks/useAggregatorCreation.ts
frontend/src/components/dashboard/aggregator/hooks/useAggregatorOptimization.ts

역할별로 코드 분리하였습니다. 
--- 
**집계자 생성에 대한 코드**는
hooks/useAggregatorCreation에 작업하시면 될 것 같습니다. 
추가적인 기능들은 components 내에 생성하여서 작업하시면 유지 보수에 용이할 것 같네요.

♻️ Refactor: Split aggregator creation by responsibility

---

frontend/src/components/dashboard/participants/dialogs/VMMonitoringDialog.tsx

Grafana의 dashboard emdeding을 이용해 모니터링 화면을 구성하였습니다.
가상머신 목록을 클릭하면 아래와 같은 대시보드를 확인할 수 있습니다.
모니터링 메트릭으로는 `CPU`, `RAM`, `Disk`, `Network Traffic`이 있습니다.
추가할 메트릭이 있으면 말씀 부탁드립니다.

✨ Enable the participants monitoring.

---

backend/scripts/aggregator_optimization.py

NSGA-II 실행하기 전 제약사항 추가하였습니다.
ram size = modelSize * participant 수 * 1.5(안전계수)로 계산하였습니다.
제약사항 기본 값으로는 4GB로 설정하였습니다. 
---
현재 프론트 연결이 잘 안되어있어서 모델 파일 크기 매개변수에 대한 작업이 필요합니다.

✨ Add new constraint for data validation

---

backend/scripts/aggregator_optimization.py
backend/scripts/requirements.txt
backend/scripts/run_optimizer.sh
backend/services/optimization.go
frontend/src/api/aggregator.ts
frontend/src/components/dashboard/aggregator/aggregator-create-content.tsx
frontend/src/components/dashboard/aggregator/aggregator.types.ts
frontend/src/components/dashboard/aggregator/components/AggregatorSettings.tsx
frontend/src/components/dashboard/aggregator/components/FederatedLearningInfo.tsx
frontend/src/components/dashboard/aggregator/components/MemoryRequirementInfo.tsx
frontend/src/components/dashboard/aggregator/hooks/useAggregatorOptimization.ts
frontend/src/components/dashboard/aggregator/utils/modelMemoryCalculator.ts

스크립트 실행으로 바꾸었습니다. 
가상환경 상에서 집계자 최적화 실행하고 
거슬렸던 input 파일은 제거하는 방향으로 문제점 개선하였습니다.
혹시 안된다면 말씀 주세요!!

♻️Update: aggregator optimization to use script-based execution

---

backend/initialization/app_init.go
backend/models/cloud_latency.go
backend/models/cloud_price.go
backend/models/provider.go
backend/models/region.go
backend/repository/cloud_latency.go
backend/repository/cloud_price.go
backend/repository/provider_repository.go
backend/repository/region_repository.go
backend/scripts/aggregator_optimization.py
backend/services/data_initialization.go

cloud_latency와 cloud_price에서 사용되는 provider, region 속성에 대해서DB 정규화를 수행하였습니다.
model
ㄴ provider.go
ㄴ region.go
router
ㄴ provider_router.go
ㄴ region_router.go

🔁 Normalize DB schema by separating region and provider columns

---

backend/services/data_initialization.go

#58 에서 cloud_price_GCP.csv 파일이 추가됨에 따라, 기존 cloud_price_AWS.csv파일만 읽던 data_initialization.go에서 모든 파일을 읽고 db를 초기화할 수 있도록 수정하였습니다.

♻️ Refactor data init code to read all price files.

---

frontend/src/components/dashboard/aggregator/aggregator-create-content.tsx
frontend/src/components/dashboard/aggregator/components/AggregatorSelectionModal.tsx
frontend/src/components/dashboard/aggregator/components/AggregatorSettings.tsx
frontend/src/components/dashboard/federated-learning/hooks/useCreateJobForm.ts

가격 범위가 너무 큰 것 같아 수정하였습니다. 
기존 100만원의 최댓값을 30만원으로,
5만원의 최솟값을 1만원으로,
step 값(한 칸씩 이동할 때마다 증감값)은 5000원으로 설정하였습니다.

🎨 Update price display range

---

backend/utils/terraform.go

파일 하나 업로드를 까먹어서...
근데 이거 없으면 안 돌아가서...

🎨 Add terraform.go

---

frontend/src/components/dashboard/layout/header.tsx

💄 Change the title of header.

---

backend/models/aggregator.go
backend/repository/aggregator_repository.go
backend/services/aggregator/service.go
frontend/src/api/aggregator.ts
frontend/src/components/dashboard/aggregator/aggregator-deploy.tsx
frontend/src/components/dashboard/aggregator/hooks/useAggregatorCreation.ts

1. 집계자 생성 시 VM, VPC 등의 리소스가 두 번 생성되는 문제가 발생함
2. DB 테이블에 집계자의 public IP와 private IP가 저장되지 않고 빈 값으로 덮어써지는 문제가 존재함
1. Frontend에서 payload가 중복 전달되던 문제를 수정하여, 한 번만 전달되도록 변경함
2. 집계자 상태 변경 시 전체 객체를 저장하지 않고, status 필드만 별도로 업데이트하도록 수정하여 IP 정보가 누락되지 않도록 개선함

🐛Fix bugs in Create Aggregator Process 

---

backend/scripts/aggregator_optimization.py
backend/services/aggregator/optimization_adapter.go
backend/services/aggregator/service.go
backend/services/optimization.go
frontend/src/api/aggregator.ts
frontend/src/components/dashboard/aggregator/components/AggregatorSettings.tsx
frontend/src/components/dashboard/aggregator/hooks/useAggregatorOptimization.ts

⚙️ Add aggregator optimization constraint with weights

---

frontend/src/components/dashboard/aggregator/aggregator-content.tsx
frontend/src/components/dashboard/aggregator/aggregator-details.tsx

- Add delete aggregator button
- Aggregator -> 집계자로 용어 통일

💄 Update UI of aggregator dashboard.

---

backend/handlers/aggregator/training.go
backend/handlers/federated_learning_handler.go
backend/initialization/app_init.go
backend/main.go
backend/services/prometheus_service.go
backend/services/virtual_machine_service.go
backend/utils/startup_script.go
backend/utils/terraform.go
frontend/src/components/dashboard/aggregator/aggregator-details.tsx
terraform/aws/main.tf
terraform/aws/terraform.tfvars
terraform/aws/variables.tf
terraform/gcp/main.tf
terraform/gcp/terraform.tfvars

- 도커 없애고 나서 프로메테우스 안들어가지던 거 해결했습니다 (aws만 검증 완료)
- 로컬에서 mlflow 포트 실행할 때 5000 아니고 5001번 포트 이용하도록 변경했습니다.
- ControlCe(Control Center Helper)라는 프로세스가 5000번에서 실행 중인데 맥 시스템 UI에 필요한 프로세스라 함부로 kill하면 안된다길래.. ㅠㅠ
- 그리고 드디어 집계자 실시간으로 컴퓨팅 자원 불러와집니다!

✨ Connect to Prometheus VM, update MLflow port (5000→5001), and retrieve Prometheus metrics

---

backend/handlers/federated_learning_handler.go

- Fix aggregator SSH authentication and readiness detection
- Resolve participant server restart issues
- Add comprehensive execution logging
- Enable end-to-end FL process flow

🎉 Complete federated learning execution pipeline.

---

frontend/src/components/dashboard/aggregator/aggregator-details.tsx

연합학습 모델 메트릭 차트를 좀 더 보기좋게 수정하였습니다.

💄 Update model metric chart.

---

backend/handlers/aggregator/handler.go
backend/handlers/aggregator/types.go
backend/services/aggregator/service.go
backend/validators/aggregator/validator.go
frontend/src/api/aggregator.ts
frontend/src/components/dashboard/aggregator/aggregator-content.tsx
frontend/src/components/dashboard/aggregator/aggregator-details.tsx
frontend/src/components/dashboard/aggregator/hooks/useAggregatorCreation.ts
frontend/src/components/dashboard/federated-learning/federated-learning-start-content.tsx

✨ Show estimated cost (monthly)

---

backend/models/cloud_latency.go
backend/scripts/aggregator_optimization.py
backend/services/data_initialization.go

1. target -> source로 계산해야하는 latency를 source -> target으로 계산하고 있던 것 수정
2. latency의 누적 값이 아닌 평균을 return하던 것과, 누적 값의 최대를 return하는 것이 아닌 souce의 latency 중 최대값을 리턴하던 오류 수정.
3. db에서 min_latency와 max_latency를 읽어서 저장할 수 있게 model 및 data_initialization.go 수정.

🐛 Fix an latency calculate error.

---

README.md

Updated the README to include Korean project description and detailed sections on project background, goals, system design, and installation instructions.

Revise README for Korean localization and project details
